# Generated by Django 4.1.7 on 2023-03-09 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioninstance',
            name='answer_choice',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
