# Generated by Django 4.1.7 on 2023-03-10 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0002_questioninstance_answer_choice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Quizzes'},
        ),
    ]
